version: '3.7'
services:
  bot:
    image: luois45/skinbaron-bot:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 0
    configs:
      # Make sure to upload a config before deploying
      - source: config1
        target: /usr/src/app/config.json
    volumes:
      # Replace my path with the path to your cookies folder
      - "/c/Users/Louis/Desktop/code/skinbaron-bot/cookies:/usr/src/app/cookies"
configs:
  config1:
    external:
      name: skinbaronbot-config
