name: GitHub Container Registry
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/luois45/skinbaron-bot:$(date +%s)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
       registry: ghcr.io
       username: ${{ secrets.GIT_USERNAME }}
       password: ${{ secrets.GIT_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
       context: .
       push: true
       tags: ghcr.io/luois45/skinbaron-bot:develop
    - name: Update Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
        repository: ghcr.io/luois45/skinbaron-bot
        readme-filepath: ./DockerHub-README.md
